

const CREATE_TAG = 'CREATE_TAG';
const DELETE_TAG = 'DELETE_TAG';

const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
const ADD_TAG_TO_DOCUMENT = 'ADD_TAG_TO_DOCUMENT';
const REMOVE_TAG_FROM_DOCUMENT = 'REMOVE_TAG_FROM_DOCUMENT';
