site:
    restart: always
    build: ./app
    expose:
        - "8000"
    volumes:
        - .:/app
    env_file: .env
    command: python app/app.py

nginx:
    build: ./nginx/
    restart: always
    ports:
        - "80:80"
    volumes:
        - /www/static
    volumes_from:
        - site
    links:
        - site:site
