# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/vivid64"

  config.vm.network "private_network", ip: "10.10.10.6"
  config.vm.host_name = "api.markdraft.dev"
  config.vm.synced_folder "./", "/var/api", id: "vagrant-root",
    :owner => "vagrant",
    :group => "vagrant",
    :mount_options => ["dmode=775","fmode=774"]
  # config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
